// Code generated by capnpc-go. DO NOT EDIT.

package dto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	dto "github.com/ApptroveLabs/apptrove-shared-models/dto/common"
)

type Header capnp.Struct

// Header_TypeID is the unique identifier for the type Header.
const Header_TypeID = 0x83384c269dd5b37a

func NewHeader(s *capnp.Segment) (Header, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Header(st), err
}

func NewRootHeader(s *capnp.Segment) (Header, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Header(st), err
}

func ReadRootHeader(msg *capnp.Message) (Header, error) {
	root, err := msg.Root()
	return Header(root.Struct()), err
}

func (s Header) String() string {
	str, _ := text.Marshal(0x83384c269dd5b37a, capnp.Struct(s))
	return str
}

func (s Header) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Header) DecodeFromPtr(p capnp.Ptr) Header {
	return Header(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Header) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Header) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Header) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Header) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Header) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Header) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Header) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Header) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Header) Value() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Header) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Header) ValueBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Header) SetValue(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// Header_List is a list of Header.
type Header_List = capnp.StructList[Header]

// NewHeader creates a new list of Header.
func NewHeader_List(s *capnp.Segment, sz int32) (Header_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Header](l), err
}

// Header_Future is a wrapper for a Header promised by a client call.
type Header_Future struct{ *capnp.Future }

func (f Header_Future) Struct() (Header, error) {
	p, err := f.Future.Ptr()
	return Header(p.Struct()), err
}

type PWAClick capnp.Struct

// PWAClick_TypeID is the unique identifier for the type PWAClick.
const PWAClick_TypeID = 0x8ade87f5da943a2c

func NewPWAClick(s *capnp.Segment) (PWAClick, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return PWAClick(st), err
}

func NewRootPWAClick(s *capnp.Segment) (PWAClick, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return PWAClick(st), err
}

func ReadRootPWAClick(msg *capnp.Message) (PWAClick, error) {
	root, err := msg.Root()
	return PWAClick(root.Struct()), err
}

func (s PWAClick) String() string {
	str, _ := text.Marshal(0x8ade87f5da943a2c, capnp.Struct(s))
	return str
}

func (s PWAClick) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PWAClick) DecodeFromPtr(p capnp.Ptr) PWAClick {
	return PWAClick(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PWAClick) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PWAClick) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PWAClick) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PWAClick) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PWAClick) Wsid() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s PWAClick) HasWsid() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PWAClick) WsidBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s PWAClick) SetWsid(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s PWAClick) Url() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s PWAClick) HasUrl() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s PWAClick) UrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s PWAClick) SetUrl(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s PWAClick) Headers() (Header_List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return Header_List(p.List()), err
}

func (s PWAClick) HasHeaders() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s PWAClick) SetHeaders(v Header_List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewHeaders sets the headers field to a newly
// allocated Header_List, preferring placement in s's segment.
func (s PWAClick) NewHeaders(n int32) (Header_List, error) {
	l, err := NewHeader_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Header_List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s PWAClick) Cuid() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s PWAClick) HasCuid() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s PWAClick) CuidBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s PWAClick) SetCuid(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

// PWAClick_List is a list of PWAClick.
type PWAClick_List = capnp.StructList[PWAClick]

// NewPWAClick creates a new list of PWAClick.
func NewPWAClick_List(s *capnp.Segment, sz int32) (PWAClick_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[PWAClick](l), err
}

// PWAClick_Future is a wrapper for a PWAClick promised by a client call.
type PWAClick_Future struct{ *capnp.Future }

func (f PWAClick_Future) Struct() (PWAClick, error) {
	p, err := f.Future.Ptr()
	return PWAClick(p.Struct()), err
}

type Click capnp.Struct

// Click_TypeID is the unique identifier for the type Click.
const Click_TypeID = 0xfdacc643e619df7e

func NewClick(s *capnp.Segment) (Click, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Click(st), err
}

func NewRootClick(s *capnp.Segment) (Click, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Click(st), err
}

func ReadRootClick(msg *capnp.Message) (Click, error) {
	root, err := msg.Root()
	return Click(root.Struct()), err
}

func (s Click) String() string {
	str, _ := text.Marshal(0xfdacc643e619df7e, capnp.Struct(s))
	return str
}

func (s Click) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Click) DecodeFromPtr(p capnp.Ptr) Click {
	return Click(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Click) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Click) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Click) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Click) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Click) Envelope() (dto.Envelope, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return dto.Envelope(p.Struct()), err
}

func (s Click) HasEnvelope() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Click) SetEnvelope(v dto.Envelope) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewEnvelope sets the envelope field to a newly
// allocated dto.Envelope struct, preferring placement in s's segment.
func (s Click) NewEnvelope() (dto.Envelope, error) {
	ss, err := dto.NewEnvelope(capnp.Struct(s).Segment())
	if err != nil {
		return dto.Envelope{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Click) Body() (PWAClick, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return PWAClick(p.Struct()), err
}

func (s Click) HasBody() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Click) SetBody(v PWAClick) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewBody sets the body field to a newly
// allocated PWAClick struct, preferring placement in s's segment.
func (s Click) NewBody() (PWAClick, error) {
	ss, err := NewPWAClick(capnp.Struct(s).Segment())
	if err != nil {
		return PWAClick{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Click_List is a list of Click.
type Click_List = capnp.StructList[Click]

// NewClick creates a new list of Click.
func NewClick_List(s *capnp.Segment, sz int32) (Click_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Click](l), err
}

// Click_Future is a wrapper for a Click promised by a client call.
type Click_Future struct{ *capnp.Future }

func (f Click_Future) Struct() (Click, error) {
	p, err := f.Future.Ptr()
	return Click(p.Struct()), err
}
func (p Click_Future) Envelope() dto.Envelope_Future {
	return dto.Envelope_Future{Future: p.Future.Field(0, nil)}
}
func (p Click_Future) Body() PWAClick_Future {
	return PWAClick_Future{Future: p.Future.Field(1, nil)}
}

const schema_fe44ff05f6d0280d = "x\xda\xbc\x93\xcfk\x13O\x18\xc6\xdfg\xde\xddo\xbe" +
	"\x95\xc6d\xddxhP\x0aR$\x96\xd64U0\xd4" +
	"\x8b\x1a\x85b=d@\xf1\xa2\xe0\xba;\xda\x90m\xb2" +
	"&M\xd7\x08\xfe\x00\x0bB\xcf^=x\xf3\xa0\x07\x15" +
	"\xff\x05\xaf\x0a\xe2A\x0fzS\xfc\x03*\xf4\xa0+\xb3" +
	"m\xb2!\x06\xf1\xe4ig^\x9ew\x9e\xe7\xb33\xef" +
	"\\\x0b'\x8cR:d\x12\xb2`\xfe\x17\xddz\xf9\xfe" +
	"\xd1\xc1s\xe5\xfbd\xedC\x94.\xbc\xfdnF\xa7\x7f" +
	"\x92)RDG\x1e#\x0f\xfb9RD\xf63\x84\x84" +
	"hf\xe1\xe1\xc7\xcd\x07\x9f6\x86\xc4\x86\x16\x8f\x89i" +
	"\xd8\x13\xba\xcf\xde+\xbe\x12\xa2\xa5\x8d\x0b\xaf\xcc\xc2\xf1" +
	"w$\xf3@t\xad\x9d\x9e\xdd\x7f}j\x9dL\xd6\xea" +
	"-\x91\x87=\xa6\x97\xb6\xc9Z\xfd\xe6\xc5\x13\xe7Xi" +
	"\xe9\x03Y\xf9Aq\x9c\xe3\x1b\xef\x82\xbd\x15\x8b7Y" +
	"\xe7\xb8\xf3y\xe2K\xe5\xf5\xd3\x1f\xa3BKc\x0fl" +
	"GG\xb2/\x1b!\x95#o\xb5Y\x0cB\xa7\xc8\xae" +
	"_s\xeb\xed\xe2\xf6\xe7\xb0\xeb\x04\x8d`aQ9\x1e" +
	"\xabV\x15\x90\xff\xb3Ad\x80\xc8:t\x80HN1" +
	"\xe4\x9c\x80\x05\xe4\xa0\x8b\xb3\xf3D\xb2\xc0\x90G\x05R" +
	"u\xd5\xc58\x09\x8c\x13&\xd7\x1c\xbf\xa3z\xbb?\xbb" +
	"U/\x9e\xacdtA\xfbe\xfb~\xce4\x91\xbc\xc4" +
	"\x90\xcb\x03~J\x87\xb8\xc2\x90\xbe\x80%D\x0e\x82\xc8" +
	"\xaa\x9d\"\x92\x1eC\xde\x13\xb0\x98s`\"\xeb\xb6n" +
	"\xbf\xc9\x90\xeb\x02\x99\xb0]\xf3zaR\x9d\x96\xdf[" +
	"\xdf]V\x8e\xa7Zm\xec&T\x19\xc8&7O\xd0" +
	"\xc5\x8c\xdbI:c\x0c\xb7\xb9\xb2\xc2\xcdFQ5\xd6" +
	"\x94\xdf\x0c\xd4\x0e\xc4\x99x\xcb\x81\x1a\x82\xc8'\x10}" +
	"\x86\xf9A\x06\x8cb\x10\xbf3p\x92c\xb2\xa5n\x9c" +
	"o\xc3$\x01s\x14C\xff\xd5\xec0\xacv\x03\xf57" +
	"\x0c\x8b\xf1AD\xff\xe8\xde+~\xcdE}\xc8\xecl" +
	"rn\xdf\xac\xa4\x7f\xc3\x0cC\x96\x05\xa2^f\"B" +
	"6\x19'\x02\xb2\x84\xcc\xd5\xa6\xd7E6\x19\xc9\xed\xf2" +
	"\xaf\x00\x00\x00\xff\xffB\xac\xd8\xb6"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_fe44ff05f6d0280d,
		Nodes: []uint64{
			0x83384c269dd5b37a,
			0x8ade87f5da943a2c,
			0xd33b2805b5558a4b,
			0xd94b313761a8b2cf,
			0xfdacc643e619df7e,
		},
		Compressed: true,
	})
}
