// Code generated by capnpc-go. DO NOT EDIT.

package dto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	dto "github.com/ApptroveLabs/apptrove-shared-models/dto/common"
)

type Header capnp.Struct

// Header_TypeID is the unique identifier for the type Header.
const Header_TypeID = 0xe914335ba7977d8e

func NewHeader(s *capnp.Segment) (Header, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Header(st), err
}

func NewRootHeader(s *capnp.Segment) (Header, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Header(st), err
}

func ReadRootHeader(msg *capnp.Message) (Header, error) {
	root, err := msg.Root()
	return Header(root.Struct()), err
}

func (s Header) String() string {
	str, _ := text.Marshal(0xe914335ba7977d8e, capnp.Struct(s))
	return str
}

func (s Header) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Header) DecodeFromPtr(p capnp.Ptr) Header {
	return Header(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Header) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Header) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Header) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Header) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Header) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Header) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Header) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Header) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Header) Value() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Header) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Header) ValueBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Header) SetValue(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// Header_List is a list of Header.
type Header_List = capnp.StructList[Header]

// NewHeader creates a new list of Header.
func NewHeader_List(s *capnp.Segment, sz int32) (Header_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Header](l), err
}

// Header_Future is a wrapper for a Header promised by a client call.
type Header_Future struct{ *capnp.Future }

func (f Header_Future) Struct() (Header, error) {
	p, err := f.Future.Ptr()
	return Header(p.Struct()), err
}

type PWAClick capnp.Struct

// PWAClick_TypeID is the unique identifier for the type PWAClick.
const PWAClick_TypeID = 0x95d9ad9756da9b8e

func NewPWAClick(s *capnp.Segment) (PWAClick, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return PWAClick(st), err
}

func NewRootPWAClick(s *capnp.Segment) (PWAClick, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return PWAClick(st), err
}

func ReadRootPWAClick(msg *capnp.Message) (PWAClick, error) {
	root, err := msg.Root()
	return PWAClick(root.Struct()), err
}

func (s PWAClick) String() string {
	str, _ := text.Marshal(0x95d9ad9756da9b8e, capnp.Struct(s))
	return str
}

func (s PWAClick) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PWAClick) DecodeFromPtr(p capnp.Ptr) PWAClick {
	return PWAClick(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PWAClick) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PWAClick) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PWAClick) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PWAClick) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PWAClick) Wsid() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s PWAClick) HasWsid() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PWAClick) WsidBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s PWAClick) SetWsid(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s PWAClick) Url() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s PWAClick) HasUrl() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s PWAClick) UrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s PWAClick) SetUrl(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s PWAClick) Headers() (Header_List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return Header_List(p.List()), err
}

func (s PWAClick) HasHeaders() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s PWAClick) SetHeaders(v Header_List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewHeaders sets the headers field to a newly
// allocated Header_List, preferring placement in s's segment.
func (s PWAClick) NewHeaders(n int32) (Header_List, error) {
	l, err := NewHeader_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Header_List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s PWAClick) Cuid() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s PWAClick) HasCuid() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s PWAClick) CuidBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s PWAClick) SetCuid(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

// PWAClick_List is a list of PWAClick.
type PWAClick_List = capnp.StructList[PWAClick]

// NewPWAClick creates a new list of PWAClick.
func NewPWAClick_List(s *capnp.Segment, sz int32) (PWAClick_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[PWAClick](l), err
}

// PWAClick_Future is a wrapper for a PWAClick promised by a client call.
type PWAClick_Future struct{ *capnp.Future }

func (f PWAClick_Future) Struct() (PWAClick, error) {
	p, err := f.Future.Ptr()
	return PWAClick(p.Struct()), err
}

type Click capnp.Struct

// Click_TypeID is the unique identifier for the type Click.
const Click_TypeID = 0xdc09371f1ba7ccd0

func NewClick(s *capnp.Segment) (Click, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Click(st), err
}

func NewRootClick(s *capnp.Segment) (Click, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Click(st), err
}

func ReadRootClick(msg *capnp.Message) (Click, error) {
	root, err := msg.Root()
	return Click(root.Struct()), err
}

func (s Click) String() string {
	str, _ := text.Marshal(0xdc09371f1ba7ccd0, capnp.Struct(s))
	return str
}

func (s Click) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Click) DecodeFromPtr(p capnp.Ptr) Click {
	return Click(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Click) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Click) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Click) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Click) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Click) Envelope() (dto.Envelope, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return dto.Envelope(p.Struct()), err
}

func (s Click) HasEnvelope() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Click) SetEnvelope(v dto.Envelope) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewEnvelope sets the envelope field to a newly
// allocated dto.Envelope struct, preferring placement in s's segment.
func (s Click) NewEnvelope() (dto.Envelope, error) {
	ss, err := dto.NewEnvelope(capnp.Struct(s).Segment())
	if err != nil {
		return dto.Envelope{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Click) Body() (PWAClick, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return PWAClick(p.Struct()), err
}

func (s Click) HasBody() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Click) SetBody(v PWAClick) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewBody sets the body field to a newly
// allocated PWAClick struct, preferring placement in s's segment.
func (s Click) NewBody() (PWAClick, error) {
	ss, err := NewPWAClick(capnp.Struct(s).Segment())
	if err != nil {
		return PWAClick{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Click_List is a list of Click.
type Click_List = capnp.StructList[Click]

// NewClick creates a new list of Click.
func NewClick_List(s *capnp.Segment, sz int32) (Click_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Click](l), err
}

// Click_Future is a wrapper for a Click promised by a client call.
type Click_Future struct{ *capnp.Future }

func (f Click_Future) Struct() (Click, error) {
	p, err := f.Future.Ptr()
	return Click(p.Struct()), err
}
func (p Click_Future) Envelope() dto.Envelope_Future {
	return dto.Envelope_Future{Future: p.Future.Field(0, nil)}
}
func (p Click_Future) Body() PWAClick_Future {
	return PWAClick_Future{Future: p.Future.Field(1, nil)}
}

const schema_e30d60fb3b9d849e = "x\xda\xac\x931k\x13a\x18\xc7\x9f\xff\xfb\xdc\x19\x95" +
	"\xc6\xe4\xbcLQ)H\x87X\xaci\x8c\xd0b\x17\xb5" +
	"\x08b\x97\xbc`u\xd0\xa1\xe7\xe5\xd5\x86\\\x933i" +
	"\x1a3\x14\x152\x09\x16:H\x07\xa9\xd0\xa9.\x1d\x14" +
	"\xfc\x16\x82\x82S\xc5\xcdA\xfa\x01\x1c\xc4\xe1\xe4\xbd6" +
	"w1FqpJ\xee\xe1\xf7\xbc\xcf\xff\xf7>\xbc\x93" +
	"\x0d\\2\x0a\xc96\x93\x909\xf3P\xb0\xf6\xe2\xd3\xcd" +
	"\x8d\x9d\xdd\xe7d\x9dD\xf0\xb2\xbb9\xf3c!\xf9\x85" +
	"L#AT\xdc\xc28\xec\xd7H\x10\xd9;\xf8J\x08" +
	"\xe6\x9e\xce\xbf5s3\x1fIf\x81\xe0^39q" +
	"\xea\xfeX\x97L\xd6\xf4\xba\xc8\xc2\xde\x12\x9a\xde\x14\x9a" +
	"~\xff\xe6\x953U\x98\xdb%+\xdb\x0fk\xa2\xf8\x84" +
	"\x8f\xc2^\xd7}\xf63n\x13\x82\x0f\xef\xb6O\x8cN" +
	"\x1d\xf9<\x90#\x84\xf7\xf88\xec\xef!\xfc-\x84\xd7" +
	"V7\xb6o\x173{\xc3\xe0y#\x0b[\xe9\xfc\xb6" +
	"c\xb4i:(/\xd7\xf3~\xdb\xc9\xb3\xebU\xdcj" +
	"3\xbf\xffs\xceu\xfc\x9a\x7f\xb1t\xeb\xf2lJ\x17" +
	"J\x80L\xb3Ad\x80\xc8r\xc6\x89\xe4\x1d\x86\\\x14" +
	"\xb0\x80\x0ctQ\x9d&\x92\x0b\x0c\xe9\x09XBd " +
	"\x88\xac\xca\x15\"Yf\xc8\xc7\x02\x16s\x06Ld\xad" +
	"\xea\xf6\x87\x0c\xd9\x15H\xb5\x9b\x952FH`\x84\x90" +
	"h5\xbc\xde\xffG\x8b\xca)\xabF\x13\xc7\x08%\x06" +
	"\xd2\xb1\x16A\x17Sn+\xee\x0c5\xdc\xfa\xd2\x12\xd7" +
	"kyU[Q^\xddW\x07\x12W\xc3O\xf6\xd5\x80" +
	"D6\x96\x88\x1c\xce\xf7;`\x98\x83\xf8\xdd\x81\xe3\x1c" +
	"\xa3\x0d\xf5\xe0F\x13&\x09\x98\xc3\x1c\xa2\xa5\x1f8," +
	"w|\xf5/\x0e\xd7\xc2\x83\x88\xb4\xc2\xe1H\xe1\x8c\xbe" +
	"\xf21\x86\x9c\xec\xdb\xc3\x84v\xc81\xe4\x05\x81DU" +
	"u\xa2h+\x8e\xd7\xfau\xd8\x1f\xf7>\xebU\\T" +
	"\x07\x86]\x8f\xcf\x8d\x86\x15\xf45\x9ce\xc8i\x81\xa0" +
	"\x97\x99\x88\x90\x8e_\x03\x01iB\xean\xbd\xdc\xd1[" +
	"\xec\xbd\xa8\xfd\xf2\xdfshmV\x8d\xfff\xfd3\x00" +
	"\x00\xff\xff\xb0\x15\xda@"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_e30d60fb3b9d849e,
		Nodes: []uint64{
			0x95d9ad9756da9b8e,
			0xd33b2805b5558a4b,
			0xd94b313761a8b2cf,
			0xdc09371f1ba7ccd0,
			0xe914335ba7977d8e,
		},
		Compressed: true,
	})
}
