// Code generated by capnpc-go. DO NOT EDIT.

package dto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type Header capnp.Struct

// Header_TypeID is the unique identifier for the type Header.
const Header_TypeID = 0xd94b313761a8b2cf

func NewHeader(s *capnp.Segment) (Header, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Header(st), err
}

func NewRootHeader(s *capnp.Segment) (Header, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Header(st), err
}

func ReadRootHeader(msg *capnp.Message) (Header, error) {
	root, err := msg.Root()
	return Header(root.Struct()), err
}

func (s Header) String() string {
	str, _ := text.Marshal(0xd94b313761a8b2cf, capnp.Struct(s))
	return str
}

func (s Header) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Header) DecodeFromPtr(p capnp.Ptr) Header {
	return Header(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Header) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Header) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Header) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Header) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Header) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Header) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Header) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Header) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Header) Value() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Header) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Header) ValueBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Header) SetValue(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// Header_List is a list of Header.
type Header_List = capnp.StructList[Header]

// NewHeader creates a new list of Header.
func NewHeader_List(s *capnp.Segment, sz int32) (Header_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Header](l), err
}

// Header_Future is a wrapper for a Header promised by a client call.
type Header_Future struct{ *capnp.Future }

func (f Header_Future) Struct() (Header, error) {
	p, err := f.Future.Ptr()
	return Header(p.Struct()), err
}

type Envelope capnp.Struct

// Envelope_TypeID is the unique identifier for the type Envelope.
const Envelope_TypeID = 0xd33b2805b5558a4b

func NewEnvelope(s *capnp.Segment) (Envelope, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Envelope(st), err
}

func NewRootEnvelope(s *capnp.Segment) (Envelope, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Envelope(st), err
}

func ReadRootEnvelope(msg *capnp.Message) (Envelope, error) {
	root, err := msg.Root()
	return Envelope(root.Struct()), err
}

func (s Envelope) String() string {
	str, _ := text.Marshal(0xd33b2805b5558a4b, capnp.Struct(s))
	return str
}

func (s Envelope) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Envelope) DecodeFromPtr(p capnp.Ptr) Envelope {
	return Envelope(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Envelope) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Envelope) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Envelope) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Envelope) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Envelope) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Envelope) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Envelope) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Envelope) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Envelope) ReqTs() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s Envelope) SetReqTs(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s Envelope) Headers() (Header_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return Header_List(p.List()), err
}

func (s Envelope) HasHeaders() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Envelope) SetHeaders(v Header_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewHeaders sets the headers field to a newly
// allocated Header_List, preferring placement in s's segment.
func (s Envelope) NewHeaders(n int32) (Header_List, error) {
	l, err := NewHeader_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Header_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s Envelope) Type() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Envelope) HasType() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Envelope) TypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Envelope) SetType(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

// Envelope_List is a list of Envelope.
type Envelope_List = capnp.StructList[Envelope]

// NewEnvelope creates a new list of Envelope.
func NewEnvelope_List(s *capnp.Segment, sz int32) (Envelope_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[Envelope](l), err
}

// Envelope_Future is a wrapper for a Envelope promised by a client call.
type Envelope_Future struct{ *capnp.Future }

func (f Envelope_Future) Struct() (Envelope, error) {
	p, err := f.Future.Ptr()
	return Envelope(p.Struct()), err
}

const schema_8424671d2d0d7366 = "x\xda|\xcf1K#Q\x14\x05\xe0s\xde\xcb\xec," +
	"K\xb2\x9bG\x02\xbb\x0c,\x82\xa4\x88B\x8cQA\xd0" +
	"F\x04AH\x93\x0b\xdaY8d\x9e&\x98d\xc6$" +
	"FS\x88\x16\xa9\xfc%\xd6\xa2\xbf\xc3\xc2\xca\xd2\xca\xca" +
	"\"?@F&\x90he\xf9\x0e\xe7\xdd{\xbf\xec\xfd" +
	"V\xaa\x92\xf9\xab\xa0\xe4\x9f\xf3#\xae\xde\xec?8\xc5" +
	"\xcd'\x88G\xc6G\xbdL\xe9\xffqa\x04G\xbb@" +
	"e\xec1G\xba\x80y\x7f\x05\xe3\xc7\xbb[\x7f\xbdR" +
	"}\x86\xf1\xbeV\x95\x0b\xac\xbe\xf0\x17s\xe3\xa4\x9b{" +
	"\xe39Jq\xd0\x0f\xcb\xf5\xb0\xdd\xd6a\xa7l;\x03" +
	"\xdb\x0a#\xbbT\xf7\xa3N\xb4\xb13y\xea\xc8\xd6H" +
	"\xc9\xea\x14\x90\"`|\x0f\x90\x03Mi(\x92y&" +
	"\x99]\x01\xe4PSZ\x8aF1O\x05\x98\xe66 " +
	"\x81\xa6\\+\x1a\xad\xf2\xd4\x80\xb9\\\x04\xe4BSF" +
	"\x8a\xba\x190\x0d\xc548\xd7\xb5\xa7{=:Pt" +
	"\xc0\xab\x86\xf5\x03\xdb\xed\xf17X\xd3d\xf6\xd3\x04&" +
	"\xe1\x9f\xfe0\xb2\xd3\xbf\xdf\x19v'\x83\x80\x84\xf0s" +
	"FX\x98\x07\xa4\xa0)\xcb\x8afj(%\x86\xa2\xa6" +
	"\xac)\xba'v8;m\xe0\xb7\xcef\xcb>\x02\x00" +
	"\x00\xff\xff\xb6<T^"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_8424671d2d0d7366,
		Nodes: []uint64{
			0xd33b2805b5558a4b,
			0xd94b313761a8b2cf,
		},
		Compressed: true,
	})
}
