// Code generated by capnpc-go. DO NOT EDIT.

package dto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	dto "github.com/ApptroveLabs/apptrove-shared-models/dto/common"
)

type PWACuid capnp.Struct

// PWACuid_TypeID is the unique identifier for the type PWACuid.
const PWACuid_TypeID = 0xa56917eed730790a

func NewPWACuid(s *capnp.Segment) (PWACuid, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return PWACuid(st), err
}

func NewRootPWACuid(s *capnp.Segment) (PWACuid, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return PWACuid(st), err
}

func ReadRootPWACuid(msg *capnp.Message) (PWACuid, error) {
	root, err := msg.Root()
	return PWACuid(root.Struct()), err
}

func (s PWACuid) String() string {
	str, _ := text.Marshal(0xa56917eed730790a, capnp.Struct(s))
	return str
}

func (s PWACuid) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PWACuid) DecodeFromPtr(p capnp.Ptr) PWACuid {
	return PWACuid(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PWACuid) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PWACuid) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PWACuid) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PWACuid) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PWACuid) Wsid() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s PWACuid) HasWsid() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PWACuid) WsidBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s PWACuid) SetWsid(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s PWACuid) Cuid() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s PWACuid) HasCuid() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s PWACuid) CuidBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s PWACuid) SetCuid(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s PWACuid) Mode() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s PWACuid) HasMode() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s PWACuid) ModeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s PWACuid) SetMode(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s PWACuid) Created() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s PWACuid) SetCreated(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

// PWACuid_List is a list of PWACuid.
type PWACuid_List = capnp.StructList[PWACuid]

// NewPWACuid creates a new list of PWACuid.
func NewPWACuid_List(s *capnp.Segment, sz int32) (PWACuid_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[PWACuid](l), err
}

// PWACuid_Future is a wrapper for a PWACuid promised by a client call.
type PWACuid_Future struct{ *capnp.Future }

func (f PWACuid_Future) Struct() (PWACuid, error) {
	p, err := f.Future.Ptr()
	return PWACuid(p.Struct()), err
}

type PWACuidMessage capnp.Struct

// PWACuidMessage_TypeID is the unique identifier for the type PWACuidMessage.
const PWACuidMessage_TypeID = 0xed76d8487cf00eea

func NewPWACuidMessage(s *capnp.Segment) (PWACuidMessage, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return PWACuidMessage(st), err
}

func NewRootPWACuidMessage(s *capnp.Segment) (PWACuidMessage, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return PWACuidMessage(st), err
}

func ReadRootPWACuidMessage(msg *capnp.Message) (PWACuidMessage, error) {
	root, err := msg.Root()
	return PWACuidMessage(root.Struct()), err
}

func (s PWACuidMessage) String() string {
	str, _ := text.Marshal(0xed76d8487cf00eea, capnp.Struct(s))
	return str
}

func (s PWACuidMessage) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PWACuidMessage) DecodeFromPtr(p capnp.Ptr) PWACuidMessage {
	return PWACuidMessage(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PWACuidMessage) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PWACuidMessage) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PWACuidMessage) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PWACuidMessage) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PWACuidMessage) Envelope() (dto.Envelope, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return dto.Envelope(p.Struct()), err
}

func (s PWACuidMessage) HasEnvelope() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PWACuidMessage) SetEnvelope(v dto.Envelope) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewEnvelope sets the envelope field to a newly
// allocated dto.Envelope struct, preferring placement in s's segment.
func (s PWACuidMessage) NewEnvelope() (dto.Envelope, error) {
	ss, err := dto.NewEnvelope(capnp.Struct(s).Segment())
	if err != nil {
		return dto.Envelope{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s PWACuidMessage) Body() (PWACuid, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return PWACuid(p.Struct()), err
}

func (s PWACuidMessage) HasBody() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s PWACuidMessage) SetBody(v PWACuid) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewBody sets the body field to a newly
// allocated PWACuid struct, preferring placement in s's segment.
func (s PWACuidMessage) NewBody() (PWACuid, error) {
	ss, err := NewPWACuid(capnp.Struct(s).Segment())
	if err != nil {
		return PWACuid{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// PWACuidMessage_List is a list of PWACuidMessage.
type PWACuidMessage_List = capnp.StructList[PWACuidMessage]

// NewPWACuidMessage creates a new list of PWACuidMessage.
func NewPWACuidMessage_List(s *capnp.Segment, sz int32) (PWACuidMessage_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[PWACuidMessage](l), err
}

// PWACuidMessage_Future is a wrapper for a PWACuidMessage promised by a client call.
type PWACuidMessage_Future struct{ *capnp.Future }

func (f PWACuidMessage_Future) Struct() (PWACuidMessage, error) {
	p, err := f.Future.Ptr()
	return PWACuidMessage(p.Struct()), err
}
func (p PWACuidMessage_Future) Envelope() dto.Envelope_Future {
	return dto.Envelope_Future{Future: p.Future.Field(0, nil)}
}
func (p PWACuidMessage_Future) Body() PWACuid_Future {
	return PWACuid_Future{Future: p.Future.Field(1, nil)}
}

const schema_ada1c3e2997cc120 = "x\xda|\x93Ak\x13Q\x14\x85\xefy71R\xda" +
	"f\x86\x09\x08\x01\x1b\x91,\xaaX\x93\xb4\x82E\x17j" +
	"\xa5P,B\x1e\x18\xdc\x08:f\x9e\xcdh\x92\x193" +
	"\x93\xc4@\xa5\x0au\xe3?p\xe9Bp\xd3\x8d\xe0\xd2" +
	"E\xf1\x07\xb8p\xa1n\xdd\x08\x82\xe2?\x18y\xd3d" +
	"&\x16\xecn\xee\xe1\xcc\x9c\xef\xbc;\xafz\x05W3" +
	"\xb5\xb9\x12\x93\x90\xe5\xec\xb1hfT\xfd\xf2\xfb\x84\xfb" +
	"\x86\xe4\x02\x10\x9d\xda\xdf~\xf5\xfd\xe3\xeb=\xcar\x8e" +
	"h\xa5\x8feX/\x90#\xb2\x9e\xe3\x07!\xda|\xd9" +
	"x\x9f]\xbc\xfc\x99d\x11\x88\x1e\x04sK'\xb7\xca" +
	"\xbbcwC\x14a)\xa1\xdd\xb6\xd0\xeeO\xef\xde\xda" +
	"\x17k\x9b\xdf\xc8,N\x9b\xb5ce\x9dg`5\xf4" +
	"{\x96\xe4!!\xfa9\xffg{\xe3\xeb\xe0\x17\x99\x0b" +
	"\xd3\x1c\xb1y\x8f\x1f\xc2\xda\x8f\xcd\x1fxH\xab\x91\x13" +
	"z\x15\x7fhWX\x0dT7\x0c\xf4\xf3\xddf\xdfu" +
	"\xce7m\xbf\xeb_\xaa\xdf.]\xbb\xdew\x9d: " +
	"\x0d\xce\x10e@d\xdag\x89\xe4\x1d\x86l\x09\x98@" +
	"\x01ZTZ\xbc\xc7\x90m\x01S\x88\x02\x04\x91\xe9j" +
	"\xd1aH_\x00\\\x00\x13\x99\x9d5\"\xd9b\xc8P" +
	" ?\x0c\\\x07\xb3$0K\xc8\xeb\xe0d\xe8x\x8e" +
	"\x9a\x0c;\xcd\x9e\xb2C\xe5 K\x02YB\x8c\xdd\xf4" +
	":\x1d\xf6\xba\x15\xd5\x1d\xa8\xb6\xe7\xab1\xf2z<\xb2" +
	"\xaf\x0e1\x17S\xe6\x04yy\x1a\x19c\xe4\xb51\xf2" +
	"3\x01\x93\xc5\x01\xf3S\xdd\xe3\x09C\xee\x0ap\x0aY" +
	"\xea\xa9\xc7\xb7\x82\x09\xd5NK\xd9\x8e\xea\x05\x98'\xd4" +
	"\x190\xd2\xbd\x11\xb4\x98\x0fG~\xd2\xe9\xa8\x0e\x1b\xf1" +
	"\x87\x88t\x85\xe3I\x853\xa7\x89d\x99!\xabS\xc7" +
	"\xbe\xa4;,2\xe4\x05\x81\xdc#5J\xd0\x06v\xbb" +
	"\xffo\x98\xdes\xe6\x7f{\x8e\xd7|S\x05\xf9\xc0\xde" +
	"R\x87ro\xa4\x11InM\x9f\xc89\x86\\\x15\x88" +
	"&\xf8D\x04#\xfd\xb7\x090\x08\xf9\xfb\x9e3\x82\x91" +
	"^\x90\x03\xf9o\x00\x00\x00\xff\xff\x92\xac\xb5i"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ada1c3e2997cc120,
		Nodes: []uint64{
			0xa56917eed730790a,
			0xd33b2805b5558a4b,
			0xd94b313761a8b2cf,
			0xed76d8487cf00eea,
		},
		Compressed: true,
	})
}
