// Code generated by capnpc-go. DO NOT EDIT.

package dto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	dto "github.com/ApptroveLabs/apptrove-shared-models/dto/common"
)

type PWAEvent capnp.Struct

// PWAEvent_TypeID is the unique identifier for the type PWAEvent.
const PWAEvent_TypeID = 0xb78d563d12bb2101

func NewPWAEvent(s *capnp.Segment) (PWAEvent, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return PWAEvent(st), err
}

func NewRootPWAEvent(s *capnp.Segment) (PWAEvent, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return PWAEvent(st), err
}

func ReadRootPWAEvent(msg *capnp.Message) (PWAEvent, error) {
	root, err := msg.Root()
	return PWAEvent(root.Struct()), err
}

func (s PWAEvent) String() string {
	str, _ := text.Marshal(0xb78d563d12bb2101, capnp.Struct(s))
	return str
}

func (s PWAEvent) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PWAEvent) DecodeFromPtr(p capnp.Ptr) PWAEvent {
	return PWAEvent(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PWAEvent) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PWAEvent) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PWAEvent) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PWAEvent) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PWAEvent) Wsid() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s PWAEvent) HasWsid() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PWAEvent) WsidBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s PWAEvent) SetWsid(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s PWAEvent) Cuid() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s PWAEvent) HasCuid() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s PWAEvent) CuidBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s PWAEvent) SetCuid(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s PWAEvent) Mode() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s PWAEvent) HasMode() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s PWAEvent) ModeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s PWAEvent) SetMode(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s PWAEvent) Created() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s PWAEvent) SetCreated(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s PWAEvent) Event() (PWAEvent_Event, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return PWAEvent_Event(p.Struct()), err
}

func (s PWAEvent) HasEvent() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s PWAEvent) SetEvent(v PWAEvent_Event) error {
	return capnp.Struct(s).SetPtr(3, capnp.Struct(v).ToPtr())
}

// NewEvent sets the event field to a newly
// allocated PWAEvent_Event struct, preferring placement in s's segment.
func (s PWAEvent) NewEvent() (PWAEvent_Event, error) {
	ss, err := NewPWAEvent_Event(capnp.Struct(s).Segment())
	if err != nil {
		return PWAEvent_Event{}, err
	}
	err = capnp.Struct(s).SetPtr(3, capnp.Struct(ss).ToPtr())
	return ss, err
}

// PWAEvent_List is a list of PWAEvent.
type PWAEvent_List = capnp.StructList[PWAEvent]

// NewPWAEvent creates a new list of PWAEvent.
func NewPWAEvent_List(s *capnp.Segment, sz int32) (PWAEvent_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[PWAEvent](l), err
}

// PWAEvent_Future is a wrapper for a PWAEvent promised by a client call.
type PWAEvent_Future struct{ *capnp.Future }

func (f PWAEvent_Future) Struct() (PWAEvent, error) {
	p, err := f.Future.Ptr()
	return PWAEvent(p.Struct()), err
}
func (p PWAEvent_Future) Event() PWAEvent_Event_Future {
	return PWAEvent_Event_Future{Future: p.Future.Field(3, nil)}
}

type PWAEvent_Event capnp.Struct

// PWAEvent_Event_TypeID is the unique identifier for the type PWAEvent_Event.
const PWAEvent_Event_TypeID = 0xdb8eefb8d4d61abb

func NewPWAEvent_Event(s *capnp.Segment) (PWAEvent_Event, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 17})
	return PWAEvent_Event(st), err
}

func NewRootPWAEvent_Event(s *capnp.Segment) (PWAEvent_Event, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 17})
	return PWAEvent_Event(st), err
}

func ReadRootPWAEvent_Event(msg *capnp.Message) (PWAEvent_Event, error) {
	root, err := msg.Root()
	return PWAEvent_Event(root.Struct()), err
}

func (s PWAEvent_Event) String() string {
	str, _ := text.Marshal(0xdb8eefb8d4d61abb, capnp.Struct(s))
	return str
}

func (s PWAEvent_Event) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PWAEvent_Event) DecodeFromPtr(p capnp.Ptr) PWAEvent_Event {
	return PWAEvent_Event(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PWAEvent_Event) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PWAEvent_Event) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PWAEvent_Event) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PWAEvent_Event) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PWAEvent_Event) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s PWAEvent_Event) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PWAEvent_Event) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s PWAEvent_Event) Revenue() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s PWAEvent_Event) HasRevenue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s PWAEvent_Event) RevenueBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetRevenue(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s PWAEvent_Event) Currency() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s PWAEvent_Event) HasCurrency() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s PWAEvent_Event) CurrencyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetCurrency(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s PWAEvent_Event) OrderId() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s PWAEvent_Event) HasOrderId() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s PWAEvent_Event) OrderIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetOrderId(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s PWAEvent_Event) ProductId() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s PWAEvent_Event) HasProductId() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s PWAEvent_Event) ProductIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetProductId(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s PWAEvent_Event) CCode() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s PWAEvent_Event) HasCCode() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s PWAEvent_Event) CCodeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetCCode(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s PWAEvent_Event) Param1() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s PWAEvent_Event) HasParam1() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s PWAEvent_Event) Param1Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetParam1(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s PWAEvent_Event) Param2() (string, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.Text(), err
}

func (s PWAEvent_Event) HasParam2() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s PWAEvent_Event) Param2Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetParam2(v string) error {
	return capnp.Struct(s).SetText(7, v)
}

func (s PWAEvent_Event) Param3() (string, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.Text(), err
}

func (s PWAEvent_Event) HasParam3() bool {
	return capnp.Struct(s).HasPtr(8)
}

func (s PWAEvent_Event) Param3Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(8)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetParam3(v string) error {
	return capnp.Struct(s).SetText(8, v)
}

func (s PWAEvent_Event) Param4() (string, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return p.Text(), err
}

func (s PWAEvent_Event) HasParam4() bool {
	return capnp.Struct(s).HasPtr(9)
}

func (s PWAEvent_Event) Param4Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(9)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetParam4(v string) error {
	return capnp.Struct(s).SetText(9, v)
}

func (s PWAEvent_Event) Param5() (string, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return p.Text(), err
}

func (s PWAEvent_Event) HasParam5() bool {
	return capnp.Struct(s).HasPtr(10)
}

func (s PWAEvent_Event) Param5Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(10)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetParam5(v string) error {
	return capnp.Struct(s).SetText(10, v)
}

func (s PWAEvent_Event) Param6() (string, error) {
	p, err := capnp.Struct(s).Ptr(11)
	return p.Text(), err
}

func (s PWAEvent_Event) HasParam6() bool {
	return capnp.Struct(s).HasPtr(11)
}

func (s PWAEvent_Event) Param6Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(11)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetParam6(v string) error {
	return capnp.Struct(s).SetText(11, v)
}

func (s PWAEvent_Event) Param7() (string, error) {
	p, err := capnp.Struct(s).Ptr(12)
	return p.Text(), err
}

func (s PWAEvent_Event) HasParam7() bool {
	return capnp.Struct(s).HasPtr(12)
}

func (s PWAEvent_Event) Param7Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(12)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetParam7(v string) error {
	return capnp.Struct(s).SetText(12, v)
}

func (s PWAEvent_Event) Param8() (string, error) {
	p, err := capnp.Struct(s).Ptr(13)
	return p.Text(), err
}

func (s PWAEvent_Event) HasParam8() bool {
	return capnp.Struct(s).HasPtr(13)
}

func (s PWAEvent_Event) Param8Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(13)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetParam8(v string) error {
	return capnp.Struct(s).SetText(13, v)
}

func (s PWAEvent_Event) Param9() (string, error) {
	p, err := capnp.Struct(s).Ptr(14)
	return p.Text(), err
}

func (s PWAEvent_Event) HasParam9() bool {
	return capnp.Struct(s).HasPtr(14)
}

func (s PWAEvent_Event) Param9Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(14)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetParam9(v string) error {
	return capnp.Struct(s).SetText(14, v)
}

func (s PWAEvent_Event) Param10() (string, error) {
	p, err := capnp.Struct(s).Ptr(15)
	return p.Text(), err
}

func (s PWAEvent_Event) HasParam10() bool {
	return capnp.Struct(s).HasPtr(15)
}

func (s PWAEvent_Event) Param10Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(15)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetParam10(v string) error {
	return capnp.Struct(s).SetText(15, v)
}

func (s PWAEvent_Event) Ev() (string, error) {
	p, err := capnp.Struct(s).Ptr(16)
	return p.Text(), err
}

func (s PWAEvent_Event) HasEv() bool {
	return capnp.Struct(s).HasPtr(16)
}

func (s PWAEvent_Event) EvBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(16)
	return p.TextBytes(), err
}

func (s PWAEvent_Event) SetEv(v string) error {
	return capnp.Struct(s).SetText(16, v)
}

// PWAEvent_Event_List is a list of PWAEvent_Event.
type PWAEvent_Event_List = capnp.StructList[PWAEvent_Event]

// NewPWAEvent_Event creates a new list of PWAEvent_Event.
func NewPWAEvent_Event_List(s *capnp.Segment, sz int32) (PWAEvent_Event_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 17}, sz)
	return capnp.StructList[PWAEvent_Event](l), err
}

// PWAEvent_Event_Future is a wrapper for a PWAEvent_Event promised by a client call.
type PWAEvent_Event_Future struct{ *capnp.Future }

func (f PWAEvent_Event_Future) Struct() (PWAEvent_Event, error) {
	p, err := f.Future.Ptr()
	return PWAEvent_Event(p.Struct()), err
}

type PWAEventMessage capnp.Struct

// PWAEventMessage_TypeID is the unique identifier for the type PWAEventMessage.
const PWAEventMessage_TypeID = 0xa7202ba06ce95189

func NewPWAEventMessage(s *capnp.Segment) (PWAEventMessage, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return PWAEventMessage(st), err
}

func NewRootPWAEventMessage(s *capnp.Segment) (PWAEventMessage, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return PWAEventMessage(st), err
}

func ReadRootPWAEventMessage(msg *capnp.Message) (PWAEventMessage, error) {
	root, err := msg.Root()
	return PWAEventMessage(root.Struct()), err
}

func (s PWAEventMessage) String() string {
	str, _ := text.Marshal(0xa7202ba06ce95189, capnp.Struct(s))
	return str
}

func (s PWAEventMessage) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PWAEventMessage) DecodeFromPtr(p capnp.Ptr) PWAEventMessage {
	return PWAEventMessage(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PWAEventMessage) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PWAEventMessage) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PWAEventMessage) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PWAEventMessage) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PWAEventMessage) Envelope() (dto.Envelope, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return dto.Envelope(p.Struct()), err
}

func (s PWAEventMessage) HasEnvelope() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PWAEventMessage) SetEnvelope(v dto.Envelope) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewEnvelope sets the envelope field to a newly
// allocated dto.Envelope struct, preferring placement in s's segment.
func (s PWAEventMessage) NewEnvelope() (dto.Envelope, error) {
	ss, err := dto.NewEnvelope(capnp.Struct(s).Segment())
	if err != nil {
		return dto.Envelope{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s PWAEventMessage) Body() (PWAEvent, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return PWAEvent(p.Struct()), err
}

func (s PWAEventMessage) HasBody() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s PWAEventMessage) SetBody(v PWAEvent) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewBody sets the body field to a newly
// allocated PWAEvent struct, preferring placement in s's segment.
func (s PWAEventMessage) NewBody() (PWAEvent, error) {
	ss, err := NewPWAEvent(capnp.Struct(s).Segment())
	if err != nil {
		return PWAEvent{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// PWAEventMessage_List is a list of PWAEventMessage.
type PWAEventMessage_List = capnp.StructList[PWAEventMessage]

// NewPWAEventMessage creates a new list of PWAEventMessage.
func NewPWAEventMessage_List(s *capnp.Segment, sz int32) (PWAEventMessage_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[PWAEventMessage](l), err
}

// PWAEventMessage_Future is a wrapper for a PWAEventMessage promised by a client call.
type PWAEventMessage_Future struct{ *capnp.Future }

func (f PWAEventMessage_Future) Struct() (PWAEventMessage, error) {
	p, err := f.Future.Ptr()
	return PWAEventMessage(p.Struct()), err
}
func (p PWAEventMessage_Future) Envelope() dto.Envelope_Future {
	return dto.Envelope_Future{Future: p.Future.Field(0, nil)}
}
func (p PWAEventMessage_Future) Body() PWAEvent_Future {
	return PWAEvent_Future{Future: p.Future.Field(1, nil)}
}

const schema_f03ac6a2556d316d = "x\xda\x8c\x94\xdfk\x1c\xd5\x1b\xc6\x9f\xe7\x9c\x99d\x93" +
	"\xecfg\xbeg\xbe(\x8b\xb2Vz\x91\xa8m~\xb5" +
	"6\x89H5\x1a0-BN\xd6\xea\x8d\xa0\xeb\xee\xd8" +
	"\x16\xb3\xd9u6?\x8c(\xa9\x10\xa1\x15+\x0a\xfe\x01" +
	"V\x10\xbdU(\x0a\xbd\xf0N\xbcPD\x8cR\x11\xa1" +
	"BA\x0b\x15#T\xa8PYyg\xdd\xdd\x19/\xa4" +
	"w\xe7\xf9\xf0&\xef\xf3\x9c\xf3\xec\x8c\x87\xea\x01g\"" +
	"\xb7\xa1\xa1\xec\x88\xdb\xd7:c\xaf,\xbfs\xf7\x1d\xef" +
	"\xc3/\xb2U\x9b\xa8\x1d{\xf7\xb3\xd9]\xb8\xaa\x1f\x98" +
	":\xc7\x17i\xce\xb3\x1f0\x1fr\x03lq\xcf\x85\xff" +
	"\xdd\xff\xf8\xd9\x8fa\x8bLN;2\xed\xab9\x9a=" +
	"\xea\x16`jT\x15\x09\xb6\x8e\xbev\xec\xbc;r\xdf" +
	"7\xb0\x05\xb2\xf5l3\xb7\xef\xf6\xe3{\xb7\xe1j\x19" +
	"\x9f\xd1\x05\x9a\x059\x9ay\xfd3\xd8\xfa\xea\xa3\x0f\xca" +
	"\x87&\x8e~\x0f\xbf\x90\x1c\x8e\x9d\x8c:\x8343\xb2" +
	"\xc6\x1ct\xc4\xc9\x85\xc2w;\x9f\xfc\xf6\xc6\x0f\xf0G" +
	"\x12\xb6\\_\x86\xdfr\"\x9a\xf7bO\xe7\x9cO5" +
	"\xa6[\xd5\xd5\xfaXc\xa3<\xe6\x84\xeb\xe1\xcajS" +
	"\xceO\xc5\xc7\xfd\x95rc\xa51\xbb\xf8\xc4\x83\xf3\"" +
	"\x1f=\x1c6\x9b\xe5\xe3\xe1\"i3\xda\x01\x1c\x02\xfe" +
	"\xe8\x11\xc0\x8eh\xda\x03\x8a>\x19P\xe0\xc4]\x80\xbd" +
	"G\xd3N+\xb6\xc2\x95\xf5p\xb9\xde\x08\x01\xd0\xeb\xc5" +
	"\x06\xe9\x81\xf9g\xea\xd5Mz=\x97m|\xd3\xa6`" +
	"\x1d&\x03s\xb2\x18s\x1bt\x1d\xbe,f^\xd0\xb4" +
	"\xdb\x09\x87\xaf\x08|I\xd3\x9eV\xf4\x95\x0a\xa8\x00\xff" +
	"U\x81\xa74\xed\xeb\x8a\xd4\x015\xe0\x9f\x99\x03\xec\xb6" +
	"\xa6}S\xd1wt@\x07\xf0\xcfN\x02\xf6\xb4\xa6}" +
	"[1\xbf\xd1<Ye\x16\x8aY0_YK\x88Z" +
	"\xbd\x1av\xc4V%\x0a\xcb\xaba\x95.\x14]\xb0\x18" +
	"\xa7\xa1\xd7\xf3\x9eH^\xa9\xd7j\xba\xbe2\xd6\xb9\xba" +
	"\x7fB\xcf\xc7R7\xe2'\xf0\xba\x01\xcb\x05\xc0>\xa9" +
	"iO(v\xf2\x85\xe2\xf0iM\xbb,\xf9\xd8\xcew" +
	"R\xb2T5\xed)E_\xabv\xc0\xe4\xf5\xe8\x9e\xf9" +
	"b\x14>\xffX\xb3\xe3v\xebDX\xae\x86Q\x93\xc3" +
	"\xe0\xa2&\xbd^!A\x81\xf9\xd5\xcdF7\xeb\x7fe" +
	"x$\xfeG\xc0\xbfZt'`\xf7j\xda\xf1\xc4\x1b" +
	"\xed\x9b\xecU\xab\xff\xb9p\xb3km\xbd\xbc\xbc\x96^" +
	"v3U\xd9\xdfn\x86,~\xb8\xb3\xd8|\xc9\x02P" +
	"\xfa\x9c\x9a\xa5\x1d\xf6v\x9b\xaf9\x07\x94\xbe\x10~\x91" +
	"\xbd\x8a\x98oy\x04(\xed\x08\xbf$\\\xb7kb~" +
	"\x8c\xe7/\x0a\xbf,\xdcq\xe2\xa6\x98\x9f\xb8\x04\x94." +
	"\x09\xbf*\xdcu\x03\xba\x80\xb9\xc2I\xa0tY\xf8\xae" +
	"\xf0\xbe\xbe\x80}\x80\xf9\x95\xb3@\xe9\x17\xe1\xd7\x84\xf7" +
	"\xf7\x07\xf1'\xe6\xf7\x98_\x15~]x&\x130\x03" +
	"\x98?b\xbe+\xfc\x86\xf0\x81\x81\x80\x03\x80\xf93\xe6" +
	"\xd7\xa8\xb9\xa4\x14\xfd\xc1\xc1\x80\x83\x80\xf9+\xc6\xd7e" +
	"\xdc\x11>4\x14p\x080T\xc2o\x08\xcf\x08\xcff" +
	"\x03f\x01\xe3\x0a_R\x9a\xa5\xac\xe0\\.`\x0e0" +
	"\x03\xf1\xb8#\xdc\x13><\x1cp\x180\xb9\x98g\x84" +
	"\x07\xc2\xf3\xf9\x80y\xc0\xf8Jn'+\xfcV\xe1\x9e" +
	"\x17\xd0\x03\xcc\xff\x95\xdc\xbe'\xfc6\x95\xaa\xdfV$" +
	"O\x98x\xe5\xcaZ\x14\x85+\x95M\xf9\x8atf\xea" +
	"Q5\x8c\x16\xba\x7f\xd3jD\xf5\xeaZeu\x01\xec" +
	"\xd5\xb8\xf2P\xe2Gx\xb8Q\x8e\xca\xb5\x89\xb4\x9cL" +
	"\xcb\xa9\xb4<\x90\x96\x07\xd3\xf2\xde\xb4<\x94\x96\xd3i" +
	"9\xd35\xde\xb61\xde\xd1:\\\xef\x1c\xff\x0e\x00\x00" +
	"\xff\xffu?I\xcb"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_f03ac6a2556d316d,
		Nodes: []uint64{
			0xa7202ba06ce95189,
			0xb78d563d12bb2101,
			0xd33b2805b5558a4b,
			0xd94b313761a8b2cf,
			0xdb8eefb8d4d61abb,
		},
		Compressed: true,
	})
}
