// Code generated by capnpc-go. DO NOT EDIT.

package dto

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	dto "github.com/ApptroveLabs/apptrove-shared-models/dto/common"
)

type Click capnp.Struct

// Click_TypeID is the unique identifier for the type Click.
const Click_TypeID = 0xdb55e318a678bce0

func NewClick(s *capnp.Segment) (Click, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return Click(st), err
}

func NewRootClick(s *capnp.Segment) (Click, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return Click(st), err
}

func ReadRootClick(msg *capnp.Message) (Click, error) {
	root, err := msg.Root()
	return Click(root.Struct()), err
}

func (s Click) String() string {
	str, _ := text.Marshal(0xdb55e318a678bce0, capnp.Struct(s))
	return str
}

func (s Click) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Click) DecodeFromPtr(p capnp.Ptr) Click {
	return Click(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Click) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Click) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Click) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Click) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Click) Envelope() (dto.Envelope, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return dto.Envelope(p.Struct()), err
}

func (s Click) HasEnvelope() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Click) SetEnvelope(v dto.Envelope) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewEnvelope sets the envelope field to a newly
// allocated dto.Envelope struct, preferring placement in s's segment.
func (s Click) NewEnvelope() (dto.Envelope, error) {
	ss, err := dto.NewEnvelope(capnp.Struct(s).Segment())
	if err != nil {
		return dto.Envelope{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Click) ClickId() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Click) HasClickId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Click) ClickIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Click) SetClickId(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Click) UserId() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Click) HasUserId() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Click) UserIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Click) SetUserId(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Click) AdId() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Click) HasAdId() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Click) AdIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Click) SetAdId(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Click) Timestamp() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s Click) SetTimestamp(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

// Click_List is a list of Click.
type Click_List = capnp.StructList[Click]

// NewClick creates a new list of Click.
func NewClick_List(s *capnp.Segment, sz int32) (Click_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[Click](l), err
}

// Click_Future is a wrapper for a Click promised by a client call.
type Click_Future struct{ *capnp.Future }

func (f Click_Future) Struct() (Click, error) {
	p, err := f.Future.Ptr()
	return Click(p.Struct()), err
}
func (p Click_Future) Envelope() dto.Envelope_Future {
	return dto.Envelope_Future{Future: p.Future.Field(0, nil)}
}

const schema_c6814fc02d95d55a = "x\xda|\x92\xbdk\x14Q\x14\xc5\xcf\xb9o\xd6\xf5#" +
	"\xba;\xec\x82\xb2 \x09b\xa1bL\xfc(4\x8dA" +
	"\x09\xb8\x82\x98+Ia\xb0p\xd8}\x90e\xbf\xc6\x9d" +
	"ML !\x11\"\xae\xa2\x90\x80\x82\x82\x8d\x8d`\xe1" +
	"\x7f`a\xa5Elm\xb4\x11R\x08VV\xb6#o" +
	"\xe2\xee\x06\x8bT3\xe7r\xef;\xf7\xfc\xde\x1b=\xca" +
	"q\xef\xec\xc1\xcf\x02\xd1\xa1\xd4\x9e\xb8\xb1\xf1\xe5\xc6\xcb" +
	"\xa5\x99'\xd0\x02\x19?:\xadC\xbf;\x7f\xb6\x902" +
	"i\xe0|\x91\x05\xe6n3\x0d\xe4\xa6\xf9\x13\x8c\x0f|" +
	"\x1b\xdf7\xb5\xb9\xf9\x0a~ag\xb3\xb8\xe6K\xb2\x9f" +
	"\xb9\xa2\xfb\xcdM\xc8}0\xfe\xf1a\xe1\xed\x91\xad\xe9" +
	"\xef\xd0\xc3d<\xf3\xf5\xc5\xf0\xc7\x9b\x0f>!\xe5\xb9" +
	"\x967\xf2+\xf7>\x99{'\x83\xc4\xc5\xb8\xdcn\x8e" +
	"\x94\x9a\xf5\xbai6Flc\xde\xd6\x9a\xa1=S\x0a" +
	"\xc2F86\x91H\x13\xdaIR\xb3\xc6\x03<\x02~" +
	"P\x00\xf4\x8e\xa1\xce\x0a\xc9<]\xcd\x9e\x03\xf4\xae\xa1" +
	"\xd6\x84\xbe0O\x01\xfc\xca\x15@\xcb\x86\xba*\xf4\x8d" +
	"\xe4i\x00\x7f\xf9\x14\xa0\x0b\x86\xba&4\x952\x07 " +
	"\x1c\x00\x07[\xf6\xdeT\xc4\x14\x84)pe\xd6\x06e" +
	"\xdb\x8ax\x08\x9c4d\xb6O\x00t\xc5L{1\xb4" +
	"\xdd\xd9\xdd2\\K\x0e\x02\\\x84\xbd\xbd\x08'\x8f\x01" +
	"z\xdcPG\x85~7\xc3\xb0\xcbp\xc2P/\x08\xd3" +
	"U\xbb\xd8[m>\xa8\xcd\xfdgV\xab\x94\xa4\x1a%" +
	"\xdf\xea?\xa7\xab\x19'\x9cO\xbe\xe7\xb3|\x1d\xd0%" +
	"C\xed\xec\xf0y\xe8\xb0\xac\x1a\xeaS\xc7J\xb6Y=" +
	"\x1e\x03t\xcdP\xd7\x1d+\xb3\xcd\xea\x99c\xd51\xd4" +
	"\xe7Bzyz\x80\xbfq\x0b\xd0uC}-\x8c\xbb" +
	"a\x010\xdb\x7fS \xb3\xe0J\xb2]\xb1\x87\xf8\xf2" +
	"\\d[}\x99\x09\xca}\x11\xb7+u\x1b\xb5\x83:" +
	"\x18v/\xe1o\x00\x00\x00\xff\xff\x9f2\x95\x82"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_c6814fc02d95d55a,
		Nodes: []uint64{
			0x8a5a7c984dcc916e,
			0x99cbcb540940da0b,
			0xdb55e318a678bce0,
		},
		Compressed: true,
	})
}
